---
name: "Donate"
guid: "eb5d7894-8eef-4b36-aa6f-5d124e828ce1"
version: "1.0.0.1"
targetAbi: "10.7.0.0"
framework: "net5.0"
overview: "Allow users to donate to your media server."
description: >
  This plugin allows users to donate to the media server you are providing.
  This could be to allow up keep of the server, fund for more movies, or just to say thanks.
category: "General"
owner: "Michael Einreinhof"
artifacts:
- "Jellyfin.Plugin.Donate.dll"
changelog: >
  removed the template items.
  added client side script to add the '@' for venmo.
